<Project>
  <Import Sdk="Microsoft.NET.Sdk" Project="Sdk.props" />

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Moq.Vsix</RootNamespace>
    <AssemblyName>Moq.Vsix</AssemblyName>
  </PropertyGroup>

  <PropertyGroup>
    <GeneratePkgDefFile>false</GeneratePkgDefFile>
    <IncludeAssemblyInVSIXContainer>false</IncludeAssemblyInVSIXContainer>
    <IncludeDebugSymbolsInVSIXContainer>true</IncludeDebugSymbolsInVSIXContainer>
    <IncludeDebugSymbolsInLocalVSIXDeployment>true</IncludeDebugSymbolsInLocalVSIXDeployment>
    <CopyBuildOutputToOutputDirectory>false</CopyBuildOutputToOutputDirectory>
    <CopyOutputSymbolsToOutputDirectory>false</CopyOutputSymbolsToOutputDirectory>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VSSDK.BuildTools" Condition="'$(MSBuildRuntimeType)' == 'Full'" />
    <PackageReference Include="Avatar" />
    <PackageReference Include="Avatar.CodeAnalysis" />
  </ItemGroup>

  <PropertyGroup>
    <StartAction>Program</StartAction>
    <StartProgram>$(DevEnvDir)devenv.exe</StartProgram>
    <StartArguments>/rootsuffix Exp</StartArguments>
  </PropertyGroup>
  
  <Import Sdk="Microsoft.NET.Sdk" Project="Sdk.targets" />
  <Import Project="$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets" Condition="Exists('$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets')" />
  
  <ItemGroup>
    <ProjectReference Include="..\Moq.CodeAnalysis\Moq.CodeAnalysis.csproj" />
    <ProjectReference Include="..\Moq.Sdk\Moq.Sdk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- https://github.com/dotnet/sdk/issues/433 -->
    <ProjectReference Update="@(ProjectReference)" AdditionalProperties="TargetFramework=netstandard2.0" />

    <!-- https://github.com/Microsoft/extendvs/issues/57 -->
    <ProjectReference Update="@(ProjectReference)" Name="%(Filename)" />
  </ItemGroup>

  <Target Name="AddPrivateAssets" BeforeTargets="GetVsixSourceItems">
    <ItemGroup>
      <VSIXSourceItem Include="@(RuntimeCopyLocalItems)"
                      Condition="'%(NuGetPackageId)' == 'Avatar' or 
                                 '%(NuGetPackageId)' == 'Avatar.CodeAnalysis'"/>
    </ItemGroup>
  </Target>

</Project>