<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuGetizer" PrivateAssets="all" />
    <PackageReference Include="IFluentInterface" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Pack="false" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Moq.Tests" />
  </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\Moq.Sdk\Moq.Sdk.csproj" />
    <ProjectReference Include="..\Moq.DynamicProxy\Moq.DynamicProxy.csproj" />
  </ItemGroup>

</Project>