using System.Collections.Generic;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Moq.CodeFixes
{
    /// <summary>
    /// Helpers to inspect and rewrite C# setups over <c>Moq.IMock&lt;T&gt;</c>.
    /// </summary>
    static class MockSyntax
    {
        /// <summary>
        /// Gets the mocked type <c>T</c> if the given type is or implements <c>Moq.IMock&lt;T&gt;</c>.
        /// </summary>
        public static ITypeSymbol? GetMockedType(ITypeSymbol? type)
        {
            if (type is not INamedTypeSymbol named)
                return null;

            return new[] { named }.Concat(named.AllInterfaces)
                .FirstOrDefault(x => x.Name == "IMock" && x.Arity == 1 && IsMoqNamespace(x.ContainingNamespace))
                ?.TypeArguments[0];
        }

        /// <summary>
        /// Whether the given symbol is a typed setup member generated by the Moq setup generator.
        /// </summary>
        public static bool IsGeneratedSetup(ISymbol? symbol)
        {
            for (var type = symbol?.ContainingType; type != null; type = type.ContainingType)
            {
                if (type.Name == "MockSetupExtensions" && IsMoqNamespace(type.ContainingNamespace))
                    return true;
            }

            return false;
        }

        /// <summary>
        /// Whether the expression is the <c>Object</c> of an <c>IMock&lt;T&gt;</c>, returning the mock expression.
        /// </summary>
        public static bool IsMockObject(ExpressionSyntax expression, SemanticModel semantic, CancellationToken cancellation, out ExpressionSyntax mock)
        {
            mock = expression;
            if (expression is not MemberAccessExpressionSyntax { Name.Identifier.ValueText: "Object" } access ||
                GetMockedType(semantic.GetTypeInfo(access.Expression, cancellation).Type) == null)
                return false;

            mock = access.Expression;
            return true;
        }

        /// <summary>
        /// Gets the outermost invocation of a fluent chain starting at the given expression, 
        /// such as <c>Setup(...).Returns(...).Once()</c>.
        /// </summary>
        public static ExpressionSyntax GetFluentChain(ExpressionSyntax expression)
        {
            while (expression.Parent is MemberAccessExpressionSyntax access && access.Expression == expression &&
                access.Parent is InvocationExpressionSyntax invocation && invocation.Expression == access)
                expression = invocation;

            return expression;
        }

        /// <summary>
        /// Finds an instance method or property with the given name in the mocked type, its base 
        /// types or its interfaces, excluding the members inherited from <see cref="object"/>.
        /// </summary>
        public static ISymbol? FindMember(ITypeSymbol mocked, string name)
        {
            IEnumerable<ITypeSymbol> types = new[] { mocked }.Concat(mocked.AllInterfaces);
            for (var type = mocked.BaseType; type != null && type.SpecialType != SpecialType.System_Object; type = type.BaseType)
                types = types.Append(type);

            return types
                .SelectMany(x => x.GetMembers(name))
                .FirstOrDefault(x => !x.IsStatic && x.CanBeReferencedByName &&
                    x.DeclaredAccessibility != Accessibility.Private &&
                    x is IMethodSymbol { MethodKind: MethodKind.Ordinary } or IPropertySymbol);
        }

        /// <summary>
        /// Creates <c>Setup(() => mock.Object.Member(...))</c> for the given member access or 
        /// invocation <paramref name="target"/> whose receiver is the given <paramref name="mock"/>.
        /// </summary>
        public static InvocationExpressionSyntax CreateSetup(ExpressionSyntax target, ExpressionSyntax mock)
        {
            var body = target.ReplaceNode(mock, MemberAccessExpression(
                SyntaxKind.SimpleMemberAccessExpression, mock.WithoutTrivia(), IdentifierName("Object")));

            return InvocationExpression(
                    IdentifierName("Setup"),
                    ArgumentList(SingletonSeparatedList(Argument(
                        ParenthesizedLambdaExpression(body.WithoutTrivia())))))
                .WithTriviaFrom(target);
        }

        /// <summary>
        /// Adds <c>using static Moq.Syntax;</c> unless the static <c>Setup</c> already binds at the given node.
        /// </summary>
        public static SyntaxNode AddSyntaxUsing(SyntaxNode root, SemanticModel semantic, SyntaxNode node)
        {
            if (semantic.LookupSymbols(node.SpanStart, name: "Setup").Any(x =>
                    x.IsStatic && x.ContainingType is { Name: "Syntax" } type && IsMoqNamespace(type.ContainingNamespace)) ||
                root is not CompilationUnitSyntax unit)
                return root;

            var name = ParseName("Moq.Syntax");
            if (unit.Usings.Any(x => x.StaticKeyword.IsKind(SyntaxKind.StaticKeyword) && x.Name?.IsEquivalentTo(name) == true))
                return root;

            return unit.AddUsings(UsingDirective(Token(SyntaxKind.StaticKeyword), null, name)
                .NormalizeWhitespace()
                .WithTrailingTrivia(EndOfLine(unit.ToFullString().Contains("\r\n") ? "\r\n" : "\n")));
        }

        static bool IsMoqNamespace(INamespaceSymbol? ns) => ns is { Name: "Moq", ContainingNamespace.IsGlobalNamespace: true };
    }
}
