//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moq.CodeFixes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moq.CodeFixes.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup mock with typed delegate for {0}.
        /// </summary>
        internal static string CustomDelegateCodeFix_TitleFormat {
            get {
                return ResourceManager.GetString("CustomDelegateCodeFix_TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A subsequent code fix for this completion will allow you to generate a 
        ///delegate to set up this method directly with the right Returns signature..
        /// </summary>
        internal static string CustomDelegateCompletion_Description {
            get {
                return ResourceManager.GetString("CustomDelegateCompletion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; binds to the mock rather than setting up &apos;{1}&apos;.
        /// </summary>
        internal static string HiddenMember_Message {
            get {
                return ResourceManager.GetString("HiddenMember_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project &apos;{0}&apos; does not reference the required Moq assembly..
        /// </summary>
        internal static string MoqRequired {
            get {
                return ResourceManager.GetString("MoqRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members invoked directly on the mocked object can be set up with the generated typed setup members of the mock instead..
        /// </summary>
        internal static string SimplifySetup_Description {
            get {
                return ResourceManager.GetString("SimplifySetup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup can be simplified to &apos;{0}&apos;.
        /// </summary>
        internal static string SimplifySetup_Message {
            get {
                return ResourceManager.GetString("SimplifySetup_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use typed setup.
        /// </summary>
        internal static string SimplifySetup_Title {
            get {
                return ResourceManager.GetString("SimplifySetup_Title", resourceCulture);
            }
        }
    }
}
