//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Reflection;
using Avatars;
using System.Runtime.CompilerServices;
using Sample;
using System.Threading;
using Moq.Sdk;
using System.Diagnostics;

namespace Mocks
{
    [DebuggerDisplay("{DebuggerDisplay,nq}")]
    public partial class ICalculatorMock : ICalculator, IAvatar, IMocked
    {
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        readonly BehaviorPipeline pipeline = new BehaviorPipeline();

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        [CompilerGenerated]
        IList<IAvatarBehavior> IAvatar.Behaviors => pipeline.Behaviors;

        [CompilerGenerated]
        public int? this[string name] { get => pipeline.Execute<int?>(MethodInvocation.Create(this, MethodBase.GetCurrentMethod(), name)); set => pipeline.Execute(MethodInvocation.Create(this, MethodBase.GetCurrentMethod(), name, value)); }

        [CompilerGenerated]
        public bool IsOn => pipeline.Execute<bool>(MethodInvocation.Create(this, MethodBase.GetCurrentMethod()));

        [CompilerGenerated]
        public CalculatorMode Mode { get => pipeline.Execute<CalculatorMode>(MethodInvocation.Create(this, MethodBase.GetCurrentMethod())); set => pipeline.Execute(MethodInvocation.Create(this, MethodBase.GetCurrentMethod(), value)); }

        [CompilerGenerated]
        public ICalculatorMemory Memory => pipeline.Execute<ICalculatorMemory>(MethodInvocation.Create(this, MethodBase.GetCurrentMethod()));

        [CompilerGenerated]
        public int Add(int x, int y) => pipeline.Execute<int>(MethodInvocation.Create(this, MethodBase.GetCurrentMethod(), x, y));
        [CompilerGenerated]
        public int Add(int x, int y, int z) => pipeline.Execute<int>(MethodInvocation.Create(this, MethodBase.GetCurrentMethod(), x, y, z));
        [CompilerGenerated]
        public void Clear(string name) => pipeline.Execute(MethodInvocation.Create(this, MethodBase.GetCurrentMethod(), name));
        [CompilerGenerated]
        public override bool Equals(object obj) => pipeline.Execute<bool>(MethodInvocation.Create(this, MethodBase.GetCurrentMethod(), obj));
        [CompilerGenerated]
        public override int GetHashCode() => pipeline.Execute<int>(MethodInvocation.Create(this, MethodBase.GetCurrentMethod()));
        [CompilerGenerated]
        public int? Recall(string name) => pipeline.Execute<int?>(MethodInvocation.Create(this, MethodBase.GetCurrentMethod(), name));
        [CompilerGenerated]
        public void Store(string name, int value) => pipeline.Execute(MethodInvocation.Create(this, MethodBase.GetCurrentMethod(), name, value));
        [CompilerGenerated]
        public override string ToString() => pipeline.Execute<string>(MethodInvocation.Create(this, MethodBase.GetCurrentMethod()));

        [CompilerGenerated]
        public bool TryAdd(ref int x, ref int y, out int? z)
        {
            z = default;
            IMethodReturn returns = pipeline.Execute(MethodInvocation.Create(this, MethodBase.GetCurrentMethod(), x, y, z));
            x = returns.Outputs.Get<int>("x");
            y = returns.Outputs.Get<int>("y");
            z = returns.Outputs.GetNullable<int>("z");
            return (bool)returns.ReturnValue;
        }

        [CompilerGenerated]
        public void TurnOn() => pipeline.Execute(MethodInvocation.Create(this, MethodBase.GetCurrentMethod()));

        [CompilerGenerated]
        public event EventHandler TurnedOn { add => pipeline.Execute<EventHandler>(MethodInvocation.Create(this, MethodBase.GetCurrentMethod(), value)); remove => pipeline.Execute<EventHandler>(MethodInvocation.Create(this, MethodBase.GetCurrentMethod(), value)); }

        #region IMocked
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        IMock mock;

        [DebuggerDisplay("Invocations = {Invocations.Count}", Name = nameof(IMocked.Mock))]
        [DebuggerBrowsable(DebuggerBrowsableState.Collapsed)]
        [CompilerGenerated]
        IMock IMocked.Mock => LazyInitializer.EnsureInitialized(ref mock, () => new DefaultMock(this));
        #endregion

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        string DebuggerDisplay => ((IMocked)this).Mock.State.TryGetValue<string>("Name", out var name) ? name : GetType().Name;
    }
}