//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Reflection;
using Avatars;
using System.Runtime.CompilerServices;
using Sample;
using System.Threading;
using Moq.Sdk;

namespace Mocks
{
    public partial class ICalculatorMemoryMock : ICalculatorMemory, IAvatar, IMocked
    {
        readonly BehaviorPipeline pipeline = new BehaviorPipeline();

        [CompilerGenerated]
        IList<IAvatarBehavior> IAvatar.Behaviors => pipeline.Behaviors;

        [CompilerGenerated]
        public void Add(int value) => pipeline.Execute(MethodInvocation.Create(this, MethodBase.GetCurrentMethod(), value));
        [CompilerGenerated]
        public void Clear() => pipeline.Execute(MethodInvocation.Create(this, MethodBase.GetCurrentMethod()));
        [CompilerGenerated]
        public override bool Equals(object obj) => pipeline.Execute<bool>(MethodInvocation.Create(this, MethodBase.GetCurrentMethod(), obj));
        [CompilerGenerated]
        public override int GetHashCode() => pipeline.Execute<int>(MethodInvocation.Create(this, MethodBase.GetCurrentMethod()));
        [CompilerGenerated]
        public int Recall() => pipeline.Execute<int>(MethodInvocation.Create(this, MethodBase.GetCurrentMethod()));
        [CompilerGenerated]
        public void Subtract(int value) => pipeline.Execute(MethodInvocation.Create(this, MethodBase.GetCurrentMethod(), value));
        [CompilerGenerated]
        public override string ToString() => pipeline.Execute<string>(MethodInvocation.Create(this, MethodBase.GetCurrentMethod()));

        #region IMocked
        IMock mock;

        [CompilerGenerated]
        IMock IMocked.Mock => LazyInitializer.EnsureInitialized(ref mock, () => new DefaultMock(this));
        #endregion
    }
}