//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Moq.Tests.RefOut;
using System.Threading;
using Moq.Sdk;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Reflection;
using Stunts;
using System.Runtime.CompilerServices;

namespace Mocks
{
    public partial class IRefOutMock : IRefOut, IStunt, IMocked
    {
        readonly BehaviorPipeline pipeline = new BehaviorPipeline();
        IMock mock;

        [CompilerGenerated]
        IList<IStuntBehavior> IStunt.Behaviors => pipeline.Behaviors;

        IMock IMocked.Mock => LazyInitializer.EnsureInitialized(ref mock, () => new DefaultMock(this));

        [CompilerGenerated]
        public override bool Equals(object obj) => pipeline.Execute<bool>(MethodInvocation.Create(this, MethodBase.GetCurrentMethod(), obj));
        [CompilerGenerated]
        public override int GetHashCode() => pipeline.Execute<int>(MethodInvocation.Create(this, MethodBase.GetCurrentMethod()));
        [CompilerGenerated]
        public override string ToString() => pipeline.Execute<string>(MethodInvocation.Create(this, MethodBase.GetCurrentMethod()));

        [CompilerGenerated]
        public bool TryParse(string input, out DateTimeOffset date)
        {
            date = default(DateTimeOffset);
            IMethodReturn returns = pipeline.Execute(MethodInvocation.Create(this, MethodBase.GetCurrentMethod(), input, date));
            date = returns.Outputs.Get<DateTimeOffset>("date");
            return (bool)returns.ReturnValue;
        }
    }
}