<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!-- When source generators are generally available in VB too, 
         we'll probably turn this into its own package and remove 
         it from the bundling into Moq package, since it won't be 
         needed most of the time. Up-front though, it will provide 
         a much needed fallback for anyone not on C# 9 , which will 
         be a sizable user base for a while. -->
    <Description>
      Provides run-time mock generation using Castle DynamicProxy, for projects that
      cannot use the compile-time mock generation provided built-in by Moq, which
      requires C# 9.0.
    </Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Mock.*.*" />
    <None Include="Mock.*.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Moq.Sdk\Moq.Sdk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NuGetizer" PrivateAssets="all" />
    <PackageReference Include="Stunts.DynamicProxy" ExcludeAssets="build;buildTransitive" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Pack="false" />
  </ItemGroup>

  <ItemGroup>
    <None Update="@(None)" PackFolder="build\netstandard2.0" />
    <PackageFile Include="@(None)" PackFolder="buildTransitive\netstandard2.0" Visible="true" />
  </ItemGroup>

</Project>
