using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Moq.CodeAnalysis
{
    /// <summary>
    /// The generated source for the setup extensions of a single mocked type.
    /// </summary>
    record MockSetup(string HintName, string Source);

    /// <summary>
    /// Identifies a mocked type by its documentation comment ID and the assembly 
    /// that defines it, since the ID alone may match types in other assemblies.
    /// </summary>
    record MockedType(string Id, string Assembly);

    static class MockSetupRenderer
    {
        const string ClassName = "MockSetupExtensions";
        const string MockSetup = "global::Moq.Sdk.IMockSetup";

        static readonly SymbolDisplayFormat typeFormat = SymbolDisplayFormat.FullyQualifiedFormat
            .AddMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

        static readonly SymbolDisplayFormat keyFormat = SymbolDisplayFormat.FullyQualifiedFormat;

        static readonly SymbolDisplayFormat docFormat = SymbolDisplayFormat.CSharpShortErrorMessageFormat;

        public static MockSetup? Render(Compilation compilation, MockedType mocked, CancellationToken cancellation)
        {
            if (compilation.GetTypeByMetadataName("Moq.Sdk.IMock`1") is not { } mockType ||
                DocumentationCommentId.GetSymbolsForReferenceId(mocked.Id, compilation)
                    .OfType<INamedTypeSymbol>()
                    .FirstOrDefault(x => x.ContainingAssembly.Identity.GetDisplayName() == mocked.Assembly) is not { } type ||
                !compilation.IsSymbolAccessibleWithin(type, compilation.Assembly))
                return null;

            // Members of IMock<T> (and object) would shadow or conflict with the extensions.
            var reserved = new HashSet<string>(mockType.AllInterfaces.Add(mockType)
                .SelectMany(x => x.MemberNames)
                .Concat(compilation.GetSpecialType(SpecialType.System_Object).MemberNames));

            var mock = mockType.Construct(type).ToDisplayString(typeFormat);
            var signatures = new HashSet<string>();
            var methods = new StringBuilder();

            foreach (var member in GetMembers(type))
            {
                cancellation.ThrowIfCancellationRequested();

                if (member.IsStatic ||
                    member.IsImplicitlyDeclared ||
                    IsObsoleteError(member) ||
                    !compilation.IsSymbolAccessibleWithin(member, compilation.Assembly))
                    continue;

                // Members inherited from other types are invoked through a cast to avoid ambiguities and hiding.
                var cast = SymbolEqualityComparer.Default.Equals(member.ContainingType, type) ?
                    null : member.ContainingType.ToDisplayString(typeFormat);

                switch (member)
                {
                    case IMethodSymbol { MethodKind: MethodKind.Ordinary } method when !reserved.Contains(method.Name):
                        RenderMethod(methods, signatures, mock, cast, method);
                        break;
                    case IPropertySymbol property when !reserved.Contains(property.IsIndexer ? property.MetadataName : property.Name):
                        if (property.GetMethod is { } getter && !IsObsoleteError(getter) && compilation.IsSymbolAccessibleWithin(getter, compilation.Assembly))
                            RenderGetter(methods, signatures, mock, cast, property);
                        if (property.SetMethod is { IsInitOnly: false } setter && !IsObsoleteError(setter) && compilation.IsSymbolAccessibleWithin(setter, compilation.Assembly))
                            RenderSetter(methods, signatures, mock, cast, property);
                        break;
                }
            }

            if (methods.Length == 0)
                return null;

            var source = new StringBuilder()
                .Append("// <auto-generated/>\n")
                .Append("#nullable enable\n")
                .Append("#pragma warning disable CS0612, CS0618\n")
                .Append('\n')
                .Append("namespace Moq\n")
                .Append("{\n")
                .Append("    static partial class ").Append(ClassName).Append('\n')
                .Append("    {\n")
                .Append(methods.ToString())
                .Append("    }\n")
                .Append("}\n")
                .ToString();

            return new MockSetup(GetHintName(mocked.Id), source);
        }

        static IEnumerable<ISymbol> GetMembers(INamedTypeSymbol type)
        {
            if (type.TypeKind == TypeKind.Interface)
            {
                return new[] { type }.Concat(type.AllInterfaces)
                    .SelectMany(x => x.GetMembers())
                    .Where(x => x.IsAbstract || x.IsVirtual);
            }

            // Base members overridden further down the hierarchy (i.e. by a sealed override) 
            // dispatch to the override, so they can only be intercepted via the override itself.
            var members = new List<ISymbol>();
            var overridden = new HashSet<ISymbol>(SymbolEqualityComparer.Default);
            for (var current = type; current is { SpecialType: not SpecialType.System_Object }; current = current.BaseType)
            {
                foreach (var member in current.GetMembers())
                {
                    if (GetOverridden(member) is { } overriddenMember)
                        overridden.Add(overriddenMember);

                    if (!overridden.Contains(member) && (member.IsAbstract || member.IsVirtual || member.IsOverride) && !member.IsSealed)
                        members.Add(member);
                }
            }

            return members;
        }

        static ISymbol? GetOverridden(ISymbol member) => member switch
        {
            IMethodSymbol method => method.OverriddenMethod,
            IPropertySymbol property => property.OverriddenProperty,
            IEventSymbol @event => @event.OverriddenEvent,
            _ => null,
        };

        static void RenderMethod(StringBuilder output, HashSet<string> signatures, string mock, string? cast, IMethodSymbol method)
        {
            if (!IsSupported(method.ReturnType) || !method.Parameters.All(x => IsSupported(x.Type)) ||
                !signatures.Add($"{method.Name}`{method.TypeParameters.Length}({string.Join(",", method.Parameters.Select(Key))})"))
                return;

            var typeParameters = method.TypeParameters.Length == 0 ? "" :
                $"<{string.Join(", ", method.TypeParameters.Select(x => Escape(x.Name)))}>";

            var names = new HashSet<string>(method.Parameters.Select(x => x.Name).Concat(method.TypeParameters.Select(x => x.Name)));
            var name = Escape(method.Name);

            RenderExtension(output, method, names, mock,
                $"{name}{typeParameters}",
                method.Parameters.Select(x => RenderParameter(x, withDefault: true)),
                RenderConstraints(method.TypeParameters),
                self => $"{Target(self, cast)}.{name}{typeParameters}({string.Join(", ", method.Parameters.Select(RenderArgument))});");
        }

        static void RenderGetter(StringBuilder output, HashSet<string> signatures, string mock, string? cast, IPropertySymbol property)
        {
            if (!IsSupported(property.Type) || !property.Parameters.All(x => IsSupported(x.Type)))
                return;

            var name = property.IsIndexer ? property.MetadataName : property.Name;
            if (!signatures.Add($"{name}`0({string.Join(",", property.Parameters.Select(Key))})"))
                return;

            var names = new HashSet<string>(property.Parameters.Select(x => x.Name));
            RenderExtension(output, property, names, mock,
                Escape(name),
                property.Parameters.Select(x => RenderParameter(x, withDefault: true)),
                "",
                self => $"_ = {Target(self, cast)}{Access(property)};");
        }

        static void RenderSetter(StringBuilder output, HashSet<string> signatures, string mock, string? cast, IPropertySymbol property)
        {
            if (!IsSupported(property.Type) || !property.Parameters.All(x => IsSupported(x.Type)))
                return;

            var name = property.IsIndexer ? property.MetadataName : property.Name;
            if (!signatures.Add($"{name}`0({string.Join(",", property.Parameters.Select(Key).Append(Key(property.Type)))})"))
                return;

            var names = new HashSet<string>(property.Parameters.Select(x => x.Name));
            var value = Unique("value", names);

            RenderExtension(output, property, names, mock,
                Escape(name),
                property.Parameters.Select(x => RenderParameter(x, withDefault: false))
                    .Append($"{property.Type.ToDisplayString(typeFormat)} {Escape(value)}"),
                "",
                self => $"{Target(self, cast)}{Access(property)} = {Escape(value)};");
        }

        static void RenderExtension(StringBuilder output, ISymbol member, HashSet<string> names, string mock,
            string name, IEnumerable<string> parameters, string constraints, Func<string, string> invocation)
        {
            var self = Escape(Unique("mock", names));
            var setup = Escape(Unique("setup", names));

            output.Append("        /// <summary>\n");
            output.Append("        /// Sets up <c>").Append(EscapeXml(member.ToDisplayString(docFormat))).Append("</c> and returns the resulting setup.\n");
            output.Append("        /// </summary>\n");

            if (GetObsolete(member) is { } obsolete)
                output.Append("        ").Append(obsolete).Append('\n');

            output.Append("        public static ").Append(MockSetup).Append(' ').Append(name)
                .Append("(this ").Append(mock).Append(' ').Append(self);

            foreach (var parameter in parameters)
                output.Append(", ").Append(parameter);

            output.Append(')').Append(constraints).Append('\n');
            output.Append("        {\n");
            output.Append("            global::Moq.Sdk.MockContext.CurrentSetup = null;\n");
            output.Append("            ").Append(invocation(self)).Append('\n');
            output.Append("            var ").Append(setup).Append(" = global::Moq.Sdk.MockContext.CurrentSetup ?? global::Moq.Sdk.CallContext.ThrowUnexpectedNull<")
                .Append(MockSetup).Append(">();\n");
            output.Append("            global::Moq.Sdk.MockExtensions.AsMock(").Append(setup).Append(".Invocation.Target).Invocations.Remove(")
                .Append(setup).Append(".Invocation);\n");
            output.Append("            return ").Append(setup).Append(";\n");
            output.Append("        }\n");
            output.Append('\n');
        }

        static string Target(string self, string? cast) => cast is null ? $"{self}.Object" : $"(({cast}){self}.Object)";

        static string Access(IPropertySymbol property) => property.IsIndexer ?
            $"[{string.Join(", ", property.Parameters.Select(RenderArgument))}]" :
            $".{Escape(property.Name)}";

        static string RenderParameter(IParameterSymbol parameter, bool withDefault)
        {
            var builder = new StringBuilder();
            if (parameter.IsParams)
                builder.Append("params ");
            if (parameter.ScopedKind == ScopedKind.ScopedValue ||
                (parameter.ScopedKind == ScopedKind.ScopedRef && parameter.RefKind != RefKind.Out))
                builder.Append("scoped ");

            builder.Append(parameter.RefKind switch
            {
                RefKind.Ref => "ref ",
                RefKind.Out => "out ",
                RefKind.In => "in ",
                RefKind.RefReadOnlyParameter => "ref readonly ",
                _ => "",
            });

            builder.Append(parameter.Type.ToDisplayString(typeFormat)).Append(' ').Append(Escape(parameter.Name));

            if (withDefault && parameter.HasExplicitDefaultValue)
                builder.Append(" = ").Append(RenderDefault(parameter));

            return builder.ToString();
        }

        static string RenderArgument(IParameterSymbol parameter) => parameter.RefKind switch
        {
            RefKind.Ref => "ref ",
            RefKind.Out => "out ",
            RefKind.In or RefKind.RefReadOnlyParameter => "in ",
            _ => "",
        } + Escape(parameter.Name);

        static string RenderDefault(IParameterSymbol parameter)
        {
            var type = parameter.Type.ToDisplayString(typeFormat);
            return parameter.ExplicitDefaultValue switch
            {
                null => "default",
                double value when double.IsNaN(value) => $"({type})(double.NaN)",
                double value when double.IsPositiveInfinity(value) => $"({type})(double.PositiveInfinity)",
                double value when double.IsNegativeInfinity(value) => $"({type})(double.NegativeInfinity)",
                float value when float.IsNaN(value) => $"({type})(float.NaN)",
                float value when float.IsPositiveInfinity(value) => $"({type})(float.PositiveInfinity)",
                float value when float.IsNegativeInfinity(value) => $"({type})(float.NegativeInfinity)",
                var value => $"({type})({SymbolDisplay.FormatPrimitive(value, quoteStrings: true, useHexadecimalNumbers: false)})",
            };
        }

        static string RenderConstraints(ImmutableArray<ITypeParameterSymbol> typeParameters)
        {
            var builder = new StringBuilder();
            foreach (var typeParameter in typeParameters)
            {
                var constraints = new List<string>();
                if (typeParameter.HasReferenceTypeConstraint)
                    constraints.Add(typeParameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated ? "class?" : "class");
                else if (typeParameter.HasUnmanagedTypeConstraint)
                    constraints.Add("unmanaged");
                else if (typeParameter.HasValueTypeConstraint)
                    constraints.Add("struct");
                else if (typeParameter.HasNotNullConstraint)
                    constraints.Add("notnull");

                constraints.AddRange(typeParameter.ConstraintTypes.Select(x => x.ToDisplayString(typeFormat)));

                if (typeParameter.HasConstructorConstraint && !typeParameter.HasValueTypeConstraint)
                    constraints.Add("new()");
                if (typeParameter.AllowsRefLikeType)
                    constraints.Add("allows ref struct");

                if (constraints.Count > 0)
                    builder.Append(" where ").Append(Escape(typeParameter.Name)).Append(" : ").Append(string.Join(", ", constraints));
            }

            return builder.ToString();
        }

        static string? GetObsolete(ISymbol member)
        {
            var attribute = FindObsolete(member) ??
                (member is IPropertySymbol property ? FindObsolete(property.GetMethod) ?? FindObsolete(property.SetMethod) : null);

            if (attribute is null)
                return null;

            var arguments = string.Join(", ", attribute.ConstructorArguments.Select(x => x.ToCSharpString()));
            return $"[global::System.Obsolete({arguments})]";
        }

        static bool IsObsoleteError(ISymbol member) => FindObsolete(member) is { } attribute &&
            attribute.ConstructorArguments.Length == 2 &&
            attribute.ConstructorArguments[1].Value is true;

        static AttributeData? FindObsolete(ISymbol? member) => member?.GetAttributes().FirstOrDefault(x =>
            x.AttributeClass is { Name: "ObsoleteAttribute", ContainingNamespace: { Name: "System", ContainingNamespace.IsGlobalNamespace: true } });

        static bool IsSupported(ITypeSymbol type) => type switch
        {
            IPointerTypeSymbol or IFunctionPointerTypeSymbol or IErrorTypeSymbol => false,
            IArrayTypeSymbol array => IsSupported(array.ElementType),
            INamedTypeSymbol named => named.TypeArguments.All(IsSupported),
            _ => true,
        };

        /// <summary>
        /// Renders a parameter for signature comparison, where C# does not distinguish
        /// between ref kinds, nullable reference annotations or method type parameter names.
        /// </summary>
        static string Key(IParameterSymbol parameter) => (parameter.RefKind == RefKind.None ? "" : "&") + Key(parameter.Type);

        static string Key(ITypeSymbol type) => type switch
        {
            ITypeParameterSymbol { TypeParameterKind: TypeParameterKind.Method } parameter => "!!" + parameter.Ordinal,
            IArrayTypeSymbol array => $"{Key(array.ElementType)}[{new string(',', array.Rank - 1)}]",
            INamedTypeSymbol { IsGenericType: true } named =>
                $"{named.OriginalDefinition.ToDisplayString(keyFormat)}<{string.Join(",", named.TypeArguments.Select(Key))}>",
            _ => type.ToDisplayString(keyFormat),
        };

        static string Unique(string name, HashSet<string> names)
        {
            while (!names.Add(name))
                name = "_" + name;

            return name;
        }

        static string Escape(string name) => SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None ? name : "@" + name;

        static string EscapeXml(string value) => value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

        static string GetHintName(string typeId)
        {
            var name = typeId.StartsWith("T:", StringComparison.Ordinal) ? typeId.Substring(2) : typeId;
            var safe = new string(name.Select(x => char.IsLetterOrDigit(x) || x is '.' or '_' or '-' ? x : '_').ToArray());

            // Sanitizing may map distinct types to the same name, so disambiguate with a stable hash.
            if (safe != name)
                safe += "." + Fnv1a(typeId).ToString("x8", CultureInfo.InvariantCulture);

            return $"{ClassName}.{safe}.g.cs";
        }

        static uint Fnv1a(string value)
        {
            var hash = 2166136261;
            foreach (var c in value)
                hash = (hash ^ c) * 16777619;

            return hash;
        }
    }
}
