name: ⚙ dotnet
description: Configures dotnet if the repo/org defines the DOTNET custom property

runs:
  using: composite
  steps:
    - name: 🔎 dotnet
      id: dotnet
      shell: pwsh
      run: |
        # Collect .NET major versions used across the repo
        $projFiles = Get-ChildItem -Recurse -Include *.*proj
        $versions = New-Object System.Collections.Generic.HashSet[string]

        foreach ($file in $projFiles) {
            $tfOutput = dotnet msbuild $file.FullName -getProperty:TargetFramework
            if ([string]::IsNullOrWhiteSpace($tfOutput)) {
                $tfOutput = dotnet msbuild $file.FullName -getProperty:TargetFrameworks
            }
            if ($tfOutput) {
                $frameworks = $tfOutput.Trim().Split(';')
                foreach ($framework in $frameworks) {
                    if ($framework -match '^net(\d+)\.\d+$') {
                        $majorVersion = $Matches[1]
                        $versions.Add($majorVersion) | Out-Null
                    }
                }
            }
        }

        $versionOutput = ($versions | ForEach-Object { "$_.x" }) -join "`n"
        "versions<<EOF" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        $versionOutput | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        "EOF" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

    - name: ⚙ dotnet
      if: steps.dotnet.outputs.versions != ''
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          ${{ steps.dotnet.outputs.versions }}
