using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Moq
{
	/// <summary>
	/// Determines the way default values are generated 
	/// calculated for loose mocks.
	/// </summary>
	public enum DefaultValue
	{
		/// <summary>
		/// Default behavior, which generates empty values for 
		/// value types (i.e. default(int)), empty array and 
		/// enumerables, and nulls for all other reference types.
		/// </summary>
		Empty,

		/// <summary>
		/// Whenever the default value generated by <see cref="Empty"/> 
		/// is null, replaces this value with a mock (if the type 
		/// can be mocked). 
		/// </summary>
		/// <remarks>
		/// For sealed classes, a null value will be generated.
		/// </remarks>
		Mock
	}
}
