<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net10.0</TargetFrameworks>
    <Nullable>annotations</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.TestPlatform.ObjectModel" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.console" />
    <PackageReference Include="xunit.runner.msbuild" Condition="'$(TargetFramework)' == 'net48'" />
    <PackageReference Include="xunit.runner.visualstudio" />

    <PackageReference Include="System.ComponentModel.Composition" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic.Features" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic.Workspaces" />
    <PackageReference Include="SQLitePCLRaw.bundle_green" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Moq.CodeAnalysis\Moq.CodeAnalysis.csproj" />
    <ProjectReference Include="..\Moq.Sdk\Moq.Sdk.csproj" />
    <ProjectReference Include="..\Moq\Moq.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Moq.Package\Mock.cs" Link="Moq\Mock.cs" />
    <Compile Include="..\Moq.Package\Mock.Overloads.cs" Link="Moq\Mock.Overloads.cs" />
    <Compile Include="..\Moq.DynamicProxy\Mock.DynamicFactory.cs" Link="Moq\Mock.DynamicFactory.cs" />
    <Compile Update="@(Compile)" CopyToOutputDirectory="PreserveNewest" />
    <None Update="@(None)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <FileConstant Include="**/*.cs" Exclude="obj/**/*.*;bin/**/*.*;Helpers/**/*.*" />
  </ItemGroup>

</Project>
