// <autogenerated />
partial class ThisAssembly
{
    partial class Strings
    {
        partial class Unknown
        {
            public static string MessageFormat => GetResourceManager("Devlooped.SponsorLink").GetString("Unknown_Message");
        }

        partial class Expiring
        {
            public static string MessageFormat => GetResourceManager("Devlooped.SponsorLink").GetString("Expiring_Message");
        }

        partial class Expired
        {
            public static string MessageFormat => GetResourceManager("Devlooped.SponsorLink").GetString("Expired_Message");
        }

        partial class Grace
        {
            public static string MessageFormat => GetResourceManager("Devlooped.SponsorLink").GetString("Grace_Message");
        }

        partial class Sponsor
        {
            public static string MessageFormat => GetResourceManager("Devlooped.SponsorLink").GetString("Sponsor_Message");
        }
    }
}